swagger: '2.0'
info:
  version: 1.0.0
  title: TV show app api
host: www.tvmaze.com
basePath: /search
schemes:
  - http
  - https
paths:
  /shows:
    get:
      tags:
        - TV shows
      summary: Get TV shows by keyword
      operationId: Search shows
      parameters:
        - in: query
          name: q
          description: Search term
          required: true
          type: string
      responses:
        '200':
          description: Request was succesfull
          schema:
            type: array
            items:
              $ref: '#/definitions/TVShow'
        '404':
          description: Not found
        '405':
          description: Invalid input
definitions:
  TVShow:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      type:
        type: string
      language:
        type: string
      genres:
        type: array
        items:
          type: string
      premiered:
        type: string
      runtime:
        type: integer
      image:
        type: object
        properties:
          medium:
            type: string
          original:
            type: string
    xml:
      name: Order
